name: Python 3.10 Workflow on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run auto_env.bat in K_make directory
      shell: cmd
      run: |
        cd K_make
        auto_env.bat

    - name: Run executer.py in K_make directory
      shell: cmd
      run: |
        cd K_make
        python executer.py

    - name: Upload output.zip
      uses: actions/upload-artifact@v4
      with:
        name: output-files
        path: K_make/output.zip
